### ISSUE TITLE
Use Retina Gravatars

### ISSUE THREAD

**Issue by chasballew** [aptible/dashboard.aptible.com#682] opened 2016-08-04 22:42 UTC
On a Retina screen, our Gravatars look le fuzz:

<img width="190" alt="screenshot 2016-08-04 18 41 11" src="https://cloud.githubusercontent.com/assets/3422584/17420794/18781fb8-5a73-11e6-8f98-f7a78f579ec9.png">

**Comment by sandersonet** [comment] 2016-08-12 20:31
Duplicate of #614

**Closed by sandersonet** 2016-08-12 20:31 UTC
