### ISSUE TITLE
Add LICENSE file.

### ISSUE THREAD

**Issue by rwjblue** [aptible/dashboard.aptible.com#484] opened 2015-10-30 19:53 UTC
I believe the license should be MIT.

@fancyremarker - Can you confirm?

**Comment by fancyremarker** [comment] 2015-10-30 20:10
Confirmed, all open source repos should be MIT. All closed-source repos should have no LICENSE.md file and call out "All rights reserved" in the README.

**Comment by fancyremarker** [comment] 2015-10-30 21:38
Dupe of aptible/support#136, but leaving open.

**Comment by rwjblue** [comment] 2015-10-30 22:37
Yeah, sorry about the duplication.  I hadn't noticed https://github.com/aptible/support/issues/136 until you mentioned it in slack.

**Closed** 2016-12-07 21:36 UTC
Labels: ready
